name: Build and Package Python Application
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r simple-python-app/requirements.txt

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test command here

      - name: Install PyInstaller
        run: |
          python -m pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile simple-python-app/src/main.py

      - name: Upload executable
        uses: actions/upload-artifact@v4.6.2
        with:
          name: my-executable
          path: dist/main
              
        #approach 2 cyclonedx-bom tool

      - name: Install SBOM tool (cyclonedx-bom)
        run: pip install cyclonedx-bom
      
      - name: Create SBOM step cyclonedx-bom
        # see for usage: https://pypi.org/project/cyclonedx-bom/
        run: cyclonedx-py requirements simple-python-app/requirements.txt -o ./sbom-action.json
      

      - name: Upload SBOM (Action)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: sbom-action
          path: sbom-action.json
          
      - name: Check for vulnerabilities
        run: |
            echo "Checking for vulnerabilities..."
            # Add your vulnerability check command here

        #Scan dependencies for vulnerabilities
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          chmod +x jfrog
          sudo mv jfrog /usr/local/bin/
         
      - name: Configure JFrog CLI
        run: |
          jfrog config add --url=${{ secrets.ARTIFACTORY_URL }} \
                          --user=${{ secrets.ARTIFACTORY_USERNAME }} \
                          --apikey=${{ secrets.ARTIFACTORY_API_KEY }} \
                          --interactive=false
          
      - name: Upload dependencies to Artifactory 
        run: |
          jfrog rt u "simple-python-app/requirements.txt" "my-repo/python-apps/requirements.txt"

      - name: Scan dependencies with JFrog Xray
        run: |
          jfrog xr scan "my-repo/python-apps/requirements.txt" || exit 1

      - name: Upload SBOM to Artifactory
        run: |
          jfrog rt u "sbom-action.json" "my-repo/sboms/sbom-action.json"

      - name: Scan SBOM with JFrog Xray
        run: |
          jfrog xr scan "my-repo/sboms/sbom-action.json" || exit 1